### ISSUE TITLE
Grab cursor op kaartje

### ISSUE THREAD

**Issue by Anna-Kyra** [KaanKalmi/connect-your-tribe-profile-card#1]
![WhatsApp Image 2024-02-08 at 10 13 36](https://github.com/KaanKalmi/connect-your-tribe-profile-card/assets/144000242/be201c72-dbfe-498d-972e-525d6e30b9b6)

Je cursor word een grab wanneer je op je profile card gaat. Waarschijnlijk heeft dit te maken met de audio die je erop heb gezet?

**Comment by KaanKalmi** [comment]
Oh nee, dit heb ik zelf gekozen ik vond de pointer lelijk 😂
